// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ITO_0pyEpzTf2SOLZyAUvPKYSt64jno',
    appId: '1:77266392273:web:67e12d1d35b054f89861f0',
    messagingSenderId: '77266392273',
    projectId: 'syaz-5773e',
    authDomain: 'syaz-5773e.firebaseapp.com',
    storageBucket: 'syaz-5773e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf-lweB04zRGXCHoaotF9HDMX_qr8ZcNc',
    appId: '1:77266392273:android:f2e132b2fcc660a29861f0',
    messagingSenderId: '77266392273',
    projectId: 'syaz-5773e',
    storageBucket: 'syaz-5773e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Zobi3Sh9-Vx9duklL7GKccpw7_aYnJU',
    appId: '1:77266392273:ios:79d93056a5a74a569861f0',
    messagingSenderId: '77266392273',
    projectId: 'syaz-5773e',
    storageBucket: 'syaz-5773e.appspot.com',
    androidClientId:
        '77266392273-g4o2bvigsvf1v3058tvn4dcs7u77mlo7.apps.googleusercontent.com',
    iosClientId:
        '77266392273-fmh1jq1qj714lde2j9qn3o3cgvc17vuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.myphone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Zobi3Sh9-Vx9duklL7GKccpw7_aYnJU',
    appId: '1:77266392273:ios:79d93056a5a74a569861f0',
    messagingSenderId: '77266392273',
    projectId: 'syaz-5773e',
    storageBucket: 'syaz-5773e.appspot.com',
    androidClientId:
        '77266392273-g4o2bvigsvf1v3058tvn4dcs7u77mlo7.apps.googleusercontent.com',
    iosClientId:
        '77266392273-fmh1jq1qj714lde2j9qn3o3cgvc17vuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.myphone',
  );
}
